Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

StringLiterals:
  EnforcedStyle: double_quotes

AllCops:
  Exclude:
    - "README.md"
    - "yoto-takemitsu.gemspec"
    - "Gemfile"

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
